### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Muzaffar41** [TheLowSpecPC/MyRepo#1]

**Comment by Muzaffar41** [comment]
It is not working in windows 11 
Founded error :
ModuleNotFoundError: No module named 'praw'

**Comment by Muzaffar41** [comment]
Please solve this problme

**Comment by TheLowSpecPC** [comment]
for the program to work, you need to use requirements.bat beforehand. you only need to use requirements.bat once if you are a new user.

**Comment by TheLowSpecPC** [comment]
I hope your problem have been solved.
