### ISSUE TITLE
composing

### ISSUE THREAD

**Issue by valeagent** [TheLowSpecPC/MyRepo#11]
I want to create a compilation with differenty sized video clips. The problem is that they get all resized to one format which makes them unwatchable.  I saw in the code: 

385 clip = clip.resize((1920, 1080))      #i tried deleting this line
446 finalClip = concatenate_videoclips(videos, method="compose")  # i tried to delete , method="compose"

somehow the clips still get resized. The documemntation of the function concatenate_videoclips() says:
 Note that the clips do not need to be the same size. If they arent’s they will all appear centered in a clip large enough to contain the biggest of them, with optionnally a color of your choosing to fill the borders.
https://zulko.github.io/moviepy/getting_started/compositing.html

but its still not happening. any ideas why the clips still get resized. i just want to connect the video clips like the definition of the function says

thanks :)

**Comment by TheLowSpecPC** [comment]
I have updated the program. Now you can download the updated program.
