### ISSUE TITLE
And how do I get the sound of the videos

### ISSUE THREAD

**Issue by fdefake** [TheLowSpecPC/MyRepo#13]
I think that some serious issue people. Its just downloading the videos, no sound. Thats weird. I saw on the internet a guy that used this script and got the audio and everything. Help! I hope someones doing some support currently.

**Comment by fdefake** [comment]
Im gonna start sending a message each day or maybe each couple of hours till someone answers so...

**Comment by fdefake** [comment]
First message: I need to get the clips with audio

**Comment by fdefake** [comment]
PLEASE DONT BAN ME

**Comment by fdefake** [comment]
I JUST WANT SOME HELP, IM BEGGING PEOPLE

**Comment by fdefake** [comment]
Hey, Im still waiting. Please someone answer.

**Comment by fdefake** [comment]
SOMEBODY HELP ME!!!

**Comment by fdefake** [comment]
Hello, this is day two of sending messages till someone answers me

**Comment by fdefake** [comment]
Another comment for the day, I know Im annoying, but Im just a begginer trying to get some answers. Sorry, please help

**Comment by TheLowSpecPC** [comment]
Its been a long time since I have worked on this project and need to read the code in order to resolve this issue which i will do later. Until then try checking if the original video itself has audio by going to the subredit.

**Comment by fdefake** [comment]
Ok, I think reddit updated their servers or something like that, some guys told me now they serve audio and video on different servers. Whatever, I gave up.

**Comment by fdefake** [comment]
Good luck
