### ISSUE TITLE
Script not working after 16/01

### ISSUE THREAD

**Issue by ricardoparrudo** [TheLowSpecPC/MyRepo#3]
So after 16 of January everytime I try to use you cool tool i get a error:
Error: Could Not Recognize Post Type, after the post is found so the script is not generating videos.

**Comment by TheLowSpecPC** [comment]
I am not getting the type of error you are so i would recommend trying to download and reinstall my program. Anyway thank you for your appreciation and support.

**Comment by ricardoparrudo** [comment]
I did a partial, i will do a full reinstall, thank you for your fast reply!
