### ISSUE TITLE
Enter Proper Details in Reddit API Settings or Downloader Settings

### ISSUE THREAD

**Issue by IAmADev78** [TheLowSpecPC/MyRepo#9]
I have done the both steps correctly but i dont know why this happening please help

![image](https://user-images.githubusercontent.com/122011847/215344852-930ff180-06bd-4439-ab80-57a23c398899.png)

![image](https://user-images.githubusercontent.com/122011847/215344871-a2e23876-e540-48f3-a561-1e82c8c47379.png)

**Comment by TheLowSpecPC** [comment]
User Agent should be the name of the developed application which you have given in the process of getting client Id and client secret. Mine look somthing like this:
![test](https://user-images.githubusercontent.com/80385481/215348302-a0822b7b-0e06-45cf-9c95-7aec239043d2.png)

**Comment by TheLowSpecPC** [comment]
Please reply if it worked for you or not.

**Comment by IAmADev78** [comment]
> User Agent should be the name of the developed application which you have given in the process of getting client Id and client secret. Mine look somthing like this: ![test](https://user-images.githubusercontent.com/80385481/215348302-a0822b7b-0e06-45cf-9c95-7aec239043d2.png)

But the tutorial i was following didnt tell about that i will change and tell you

**Comment by IAmADev78** [comment]
didn't work same error is there any specified version of python which i have to use ? i am using latest

**Comment by IAmADev78** [comment]
![image](https://user-images.githubusercontent.com/122011847/215349665-0ed05cf2-f723-4623-bfd7-3c20f7c1327b.png)

**Comment by TheLowSpecPC** [comment]
> didn't work same error is there any specified version of python which i have to use ? i am using latest

I will see into the issue. Anyway can you sent me the link to the tutorial as soon as possible.

**Comment by IAmADev78** [comment]
> > didn't work same error is there any specified version of python which i have to use ? i am using latest
> 
> I will see into the issue. Anyway can you sent me the link to the tutorial as soon as possible.

sure sending it right away https://www.youtube.com/watch?v=IjixCp2pA5M

**Comment by Zaid-maker** [comment]
Any fix?
